version: '3.5'

services:

  postgres:
    image: 'postgres:latest'
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - "${PWD}/postgres-data:/var/lib/postgresql/data/"

  roach1:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"
    command:
      - start
      - --insecure
      - --advertise-addr=roach1:26357
      - --http-addr=roach1:8080
      - --listen-addr=roach1:26357
      - --sql-addr=roach1:26257
      - --insecure
      - --join=roach1:26357,roach2:26357,roach3:26357
    # volumes:
    #   - "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"

  roach2:
    image: cockroachdb/cockroach:latest
    ports:
      - "26258:26258"
      - "8081:8081"
    command:
      - start
      - --insecure
      - --advertise-addr=roach2:26357
      - --http-addr=roach2:8081
      - --listen-addr=roach2:26357
      - --sql-addr=roach2:26258
      - --insecure
      - --join=roach1:26357,roach2:26357,roach3:26357
    # volumes:
    #   - "${PWD}/cockroach-data/roach2:/cockroach/cockroach-data"

  roach3:
    image: cockroachdb/cockroach:latest
    ports:
      - "26259:26259"
      - "8082:8082"
    command:
      - start
      - --insecure
      - --advertise-addr=roach3:26357
      - --http-addr=roach3:8082
      - --listen-addr=roach3:26357
      - --sql-addr=roach3:26259
      - --insecure
      - --join=roach1:26357,roach2:26357,roach3:26357
    # volumes:
    #   - "${PWD}/cockroach-data/roach3:/cockroach/cockroach-data"
